apiVersion: v1
kind: Secret
meta
  name: mysql-secret
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: "RootPass!2024Secure"
  MYSQL_DATABASE: "vetcare"
  MYSQL_USER: "vetcare_app"
  MYSQL_PASSWORD: "AppPass!2024Secure"