apiVersion: v1
kind: Service
metadata:
  name: vetcare-service
spec:
  selector:
    app: vetcare
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8085
      nodePort: 30080
  type: NodePort