# config/routes.yaml

# Import automatique des controllers avec annotations/attributes
controllers:
  resource: ../src/Controller/
  type: attribute

# Route vers la page d'accueil / index
app_user_index:
  path: /
  controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::template
  defaults:
    template: 'security/index.html.twig'
