app_home:
    path: /
    controller: App\Controller\HomeController::index

app_client_interface:
    path: /client
    controller: App\Controller\HomeController::clientInterface

app_login:
    path: /login
    controller: App\Controller\SecurityController::login

app_logout:
    path: /logout
    controller: App\Controller\SecurityController::logout

app_medicament:
    resource: '../src/Controller/MedicamentController.php'
    type: attribute

app_traitement:
    resource: '../src/Controller/TraitementController.php'
    type: attribute