parameters:
  dossier_medical_images_dir: '%kernel.project_dir%/public/uploads/dossier_medical'

services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  App\:
    resource: '../src/'
    exclude:
      - '../src/DependencyInjection/'
      - '../src/Entity/'
      - '../src/Kernel.php'

  App\Controller\:
    resource: '../src/Controller/'
    tags: ['controller.service_arguments']
    bind:
      $dossierMedicalImagesDir: '%dossier_medical_images_dir%'
